### ISSUE TITLE
Error from console

### ISSUE THREAD

**Issue by vick2075** [tjczec01/butcher#2]
Traceback (most recent call last):
  File "C:/Users/dell/Desktop/ODEs/butcherrad.py", line 5, in <module>
    A, B, C = X.radau()
  File "C:\Program Files\Python38\lib\site-packages\butchertableau\butchertableau.py", line 231, in radau
    As = self.Ai(self.s, Bs, Cs)
  File "C:\Program Files\Python38\lib\site-packages\butchertableau\butchertableau.py", line 221, in Ai
    linans = list(Aslin.args[:][0])
IndexError: tuple index out of range

**Comment by tjczec01** [comment]
I am not sure how this error results from running the program. Can you let me know what operating system you are using? What order are you running?

**Comment by vick2075** [comment]
Hi,

I just took the example provided in your documentation. My operating system and hardware is as follows:
Windows 10 Home
x-64
Python 3.8.3
scipy 1.4.1
numpy 1.23.5
Using IDLE
Tk version 8.6.9

**Comment by tjczec01** [comment]
Can you please try downloading anaconda?
https://www.anaconda.com/products/distribution
I have tested this from orders of 7 - 17, the other number is the numerical accuracy that you require, in general I don't think that this should be required for most uses but I wanted to build this for as many use cases as I could, as this would mean that you require solutions that necessitate the use of numbers beyond the normal bounds of floats in python. I have tested this on both Windows 10 & 11 and it seems to work fine. I used a normal-high end-ish laptop to compute the results of both order 7 & 17 and at most I waited 5~10 minutes. I can not seem to replicate the error that you are producing.

**Comment by vick2075** [comment]
You want me to run the code in Jupyter Notebook?

**Comment by tjczec01** [comment]
I would personally download and install the package using pip if I wanted to follow the given example.

**Comment by vick2075** [comment]
I'm running it on Notebook using anaconda which I already have. It's taking quite a bit of time! But what I don't understand is, why would it work on Anaconda and not on Basic Python installation IDLE?

**Comment by tjczec01** [comment]
These answers may help:

1. https://stackoverflow.com/questions/53490310/why-is-an-amd-ryzen-2700x-2x-slower-than-a-3-year-old-laptop-intel-i7-6820hq-wit

2. https://stackoverflow.com/questions/53368253/what-is-the-difference-between-spyder-and-jupyter

**Comment by vick2075** [comment]
Actually it ran under 3 minutes or 2 on my other laptop. It actually worked as well on IDLE Python. I guess it's the hardware:
my other laptop is at i7 2.7GHz 8GB RAM and this one is at i5 2.5 GHz 4 GB RAM.

Thanks a lot!
